name = "jadkel-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
JWT_SECRET = "jadkel-secret-change-in-production"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"

[[d1_databases]]
binding = "DB"
database_name = "jadkel-db"
database_id = "4f81fd12-ae04-4f5c-9d01-2eda6f71599e"

[[kv_namespaces]]
binding = "SESSIONS"
id = "254db68285bc4be99809885790453e42"

[dev]
port = 8787
